#pragma once

// GLOBAL BABAJI (3.3.0) 
//SDK GENERATED BY @mariopc2

namespace SDK
{
//---------------------By ARMP---------------------------
//Enums
//---------------------By ARMP---------------------------

// UserDefinedEnum EnumAvatarSlotNameConfig.EnumAvatarSlotNameConfig
enum class EnumAvatarSlotNameConfig : uint8_t
{
	EnumAvatarSlotNameConfig__NewEnumerator0 = 0,
	EnumAvatarSlotNameConfig__NewEnumerator1 = 1,
	EnumAvatarSlotNameConfig__NewEnumerator2 = 2,
	EnumAvatarSlotNameConfig__NewEnumerator4 = 3,
	EnumAvatarSlotNameConfig__NewEnumerator3 = 4,
	EnumAvatarSlotNameConfig__NewEnumerator5 = 5,
	EnumAvatarSlotNameConfig__NewEnumerator6 = 6,
	EnumAvatarSlotNameConfig__NewEnumerator7 = 7,
	EnumAvatarSlotNameConfig__EnumAvatarSlotNameConfig_MAX = 8
};



}

