#pragma once

// GLOBAL BABAJI (3.3.0) 
//SDK GENERATED BY @mariopc2

#include "../SDK.hpp"

namespace SDK
{
//---------------------By ARMP---------------------------
//Parameters
//---------------------By ARMP---------------------------

// Function JsEnv.DynamicDelegateProxy.Fire
struct UDynamicDelegateProxy_Fire_Params
{
};

}

