#pragma once

// GLOBAL BABAJI (3.3.0) 
//SDK GENERATED BY @mariopc2

namespace SDK
{
//---------------------By ARMP---------------------------
//Enums
//---------------------By ARMP---------------------------

// UserDefinedEnum EnumAvatarForceGender.EnumAvatarForceGender
enum class EnumAvatarForceGender : uint8_t
{
	EnumAvatarForceGender__NewEnumerator0 = 0,
	EnumAvatarForceGender__NewEnumerator1 = 1,
	EnumAvatarForceGender__NewEnumerator2 = 2,
	EnumAvatarForceGender__EnumAvatarForceGender_MAX = 3
};



}

