#pragma once

// GLOBAL BABAJI (3.3.0) 
//SDK GENERATED BY @mariopc2

#include "../SDK.hpp"

namespace SDK
{
//---------------------By ARMP---------------------------
//Parameters
//---------------------By ARMP---------------------------

// Function SettingConfig.SettingConfig_C.ConditionSetFireGyroData
struct USettingConfig_C_ConditionSetFireGyroData_Params
{
};

// Function SettingConfig.SettingConfig_C.Init
struct USettingConfig_C_Init_Params
{
};

}

